### ISSUE TITLE
2023-11-8 TODO

### ISSUE THREAD

**Issue by Paul2021-R** [peer-42seoul/test#3]

**Comment by Paul2021-R** [comment]
- [ ] 백엔드 API 컴펌
- [ ] ~~~

**Comment by sinryuji** [comment]
- [ ] ㅎㅇ

**Comment by heehoh** [comment]
- [ ] 오늘 해야할 일

**Comment by KRimwoo** [comment]
- [ ] 로그인 reissue 오류 처리
- [ ] 저녁 먹기

**Comment by juhyeonlee134** [comment]
- [ ] ㅇ

**Comment by weejihye** [comment]
[] 배고파요

**Comment by SaltySalt77** [comment]
- [ ] 운영진 업무
    - [ ] 연합 동아리 의견 전달

**Comment by KRimwoo** [comment]
> * [x]  백엔드 API 컴펌
> * [x]  ~~~

quote reply는 뭐져

**Comment by wochae** [comment]
- [ ] 테스트

**Comment by Paul2021-R** [comment]
> > * [x]   백엔드 API 컴펌
> > * [x]   ~~~
> 
> quote reply는 뭐져
이런겁니다

**Comment by SaltySalt77** [comment]
- [ ] 추가 작업
    - 관련 이슈 [이슈](https://github.com/peer-42seoul/Peer-Frontend/issues/183)

**Comment by Paul2021-R** [comment]
========================================================================================
